[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-systems"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "torchcodec==0.7.0",
    "numpy",
    "pandas",
    "matplotlib",
    "psutil",
]

[project.optional-dependencies]
dev = [
    "jupyterlab",
    "ipykernel",
    "pytest",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]